InsurancePremiumCalc.Presentation/Models/ErrorViewModel.cs
namespace InsurancePremiumCalc.Presentation.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InsurancePremiumCalc.Presentation/Controllers/HomeController.cs
using InsurancePremiumCalc.Presentation.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace InsurancePremiumCalc.Presentation.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InsurancePremiumCalc.Presentation/Controllers/PremiumController.cs
using InsurancePremiumCalc.Application.Interfaces;
using InsurancePremiumCalc.Domain.DTO_s;
using InsurancePremiumCalc.Presentation.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;
using System.Numerics;

namespace InsurancePremiumCalc.Presentation.Controllers
{
    public class PremiumController : Controller
    {
        private readonly ILogger<PremiumController> _logger;
        private readonly IPremiumService _premiumService;
     

        public PremiumController(ILogger<PremiumController> logger, IPremiumService premiumService)
        {
            _logger = logger;
            _premiumService = premiumService;
        }

      

        public IActionResult Index()
        {
            //var occupations = new List<(string Name, double value)>
            // {
            //     ("Cleaner (Light Manual)", 11.50),
            //     ("Doctor (Professional)", 1.5),
            //     ("Author (White Collar)", 2.25),
            //     ("Farmer (Heavy Manual)", 31.75),
            //     ("Mechanic (Heavy Manual)", 31.75),
            //     ("Florist (Light Manual)", 11.50),
            //     ("Other (Heavy Manual)", 31.75)
            // };

            //ViewBag.Occupations = occupations;

            return View();
        }
        [HttpPost]
        public async Task<decimal> CalculatePrimium( int Age, decimal Factor, decimal SumInsured)
        {
            var request = new PremiumRequest
            {
                Age = Age,
                Factor = Factor,
                SumInsured = SumInsured
            };

            return await _premiumService.CalculateAsync(request);           
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InsurancePremiumCalc.Presentation/Views/Premium/Index.cshtml
@{
    ViewData["Title"] = "Calculate Premium";
}







    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-12 col-md-6 col-lg-4">
                <h2 class="mb-4 text-center">Monthly Premium Calculator</h2>

                <form id="premiumForm">
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input id="name" type="text" class="form-control" required>
                    </div>

                    <div class="mb-3">
                        <label for="age" class="form-label">Age Next Birthday</label>
                        <input id="age" type="number" class="form-control" required>
                    </div>

                    <div class="mb-3">
                        <label for="dob" class="form-label">Date of Birth (MM/YYYY)</label>
                        <input id="dob" type="month" class="form-control" required>
                    </div>

                    <div class="mb-3">
                        <label for="occupation" class="form-label">Usual Occupation</label>
                        <select id="occupation" class="form-select" onchange="calculatePremium()" required>
                            <option value="">-- Select --</option>
                            <option value="11.50">Cleaner (Light Manual)</option>
                            <option value="1.5">Doctor (Professional)</option>
                            <option value="2.25">Author (White Collar)</option>
                            <option value="31.75">Farmer (Heavy Manual)</option>
                            <option value="31.75">Mechanic (Heavy Manual)</option>
                            <option value="11.50">Florist (Light Manual)</option>
                            <option value="31.75">Other (Heavy Manual)</option>
                        </select>
                    </div>

                    <div class="mb-3">
                        <label for="sumInsured" class="form-label">Death – Sum Insured</label>
                        <input id="sumInsured" type="number" class="form-control" required oninput="calculatePremium()">
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Monthly Premium</label>
                    <div id="premium" class="p-3 bg-light border rounded text-center">₹0.00</div>
                    </div>
                <div class="mb-3" id="result">
                    
                </div>
                </form>
            </div>
        </div>
    </div>
    <script>
    function calculatePremium(){

        const age = parseFloat($("#age").val());
        const factor = parseFloat($("#occupation").val());
        const sumInsured = parseFloat($("#sumInsured").val());
      
        if (factor > 0 && factor != '') {
            $.ajax({
                url: '@Url.Action("CalculatePrimium", "Premium")', // Controller Action URL
                type: 'POST',
                data: { Age: age, Factor: factor, SumInsured: sumInsured },
                success: function (data) {
                    // if (data.success) {
                    console.log(data);
                    $("#premium").html("₹" + data);
                    // } else {
                    //     $("#result").html("Error occurred");
                    // }
                },
                error: function (xhr, status, error) {
                    $("#result").html("AJAX Error: " + error);
                }
            });
        }
    }
    </script>
 

InsurancePremiumCalc.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Insurance Premium Calculation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InsurancePremiumCalc.Presentation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Premium" asp-action="Index">Insurance Premium Calculation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Insurance Premium Calculation @* - <a asp-area="" asp-controller="Premium" asp-action="Privacy">Privacy</a> *@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>